handleGHRelease: true
manifest: true
releaseType: maven
bumpMinorPreMajor: true

branches:
  - branch: main
    releaseType: maven
    handleGHRelease: true
    manifest: true
    manifestFile: .release-please-manifest.json
    manifestConfig: release-please-config.json